# Generated by Django 3.2.6 on 2021-12-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Nuevo'), (1, 'En progreso'), (2, 'En revisión'), (3, 'En espera'), (4, 'Cerrado'), (5, 'Eliminado')], default=0, verbose_name='Estado'),
        ),
    ]
