# Generated by Django 3.2.6 on 2021-11-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_contact_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Clients.client'),
        ),
    ]
