# Generated by Django 3.2.6 on 2021-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.SmallIntegerField(choices=[(0, 'Project Management'), (1, 'Sales'), (2, 'Requirements'), (3, 'User Experience'), (4, 'Development'), (5, 'Quality Assurance'), (6, 'Testing'), (7, 'Maintenance')], default=0, verbose_name='Area'),
        ),
    ]
