<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-11-08 22:35
=======
# Generated by Django 3.2.6 on 2021-11-08 22:32
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
